
package com.sds.acube.luxor.webservice;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.3.0
 * Thu Jul 04 09:40:08 KST 2013
 * Generated source version: 2.3.0
 * 
 */
 
public class LuxorWebServiceServer{

    protected LuxorWebServiceServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new com.sds.acube.luxor.webservice.LuxorWebServiceImpl();
        String address = "http://localhost:9090/LuxorWebServiceImplPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new LuxorWebServiceServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 