
package com.sds.acube.luxor.ws.client.sch;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SchScheduleService", targetNamespace = "http://ws.sch.collaboration.luxor.acube.sds.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SchScheduleService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.sch.Page
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPagingList", targetNamespace = "http://ws.sch.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.sch.GetPagingList")
    @ResponseWrapper(localName = "getPagingListResponse", targetNamespace = "http://ws.sch.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.sch.GetPagingListResponse")
    public Page getPagingList(
        @WebParam(name = "arg0", targetNamespace = "")
        SearchVO arg0);

}
