
package com.sds.acube.luxor.ws.client.sch;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SchScheduleServiceImplService", targetNamespace = "http://ws.sch.collaboration.luxor.acube.sds.com/", wsdlLocation = "http://127.0.0.1:8080/luxor_collaboration/cxf-jaxws/MobileScheduleWebService?wsdl")
public class SchScheduleServiceImplService
    extends Service
{

    private final static URL SCHSCHEDULESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SCHSCHEDULESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SCHSCHEDULESERVICEIMPLSERVICE_QNAME = new QName("http://ws.sch.collaboration.luxor.acube.sds.com/", "SchScheduleServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/luxor_collaboration/cxf-jaxws/MobileScheduleWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCHSCHEDULESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SCHSCHEDULESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SchScheduleServiceImplService() {
        super(__getWsdlLocation(), SCHSCHEDULESERVICEIMPLSERVICE_QNAME);
    }

    public SchScheduleServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCHSCHEDULESERVICEIMPLSERVICE_QNAME, features);
    }

    public SchScheduleServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SCHSCHEDULESERVICEIMPLSERVICE_QNAME);
    }

    public SchScheduleServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCHSCHEDULESERVICEIMPLSERVICE_QNAME, features);
    }

    public SchScheduleServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SchScheduleServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SchScheduleService
     */
    @WebEndpoint(name = "SchScheduleServiceImplPort")
    public SchScheduleService getSchScheduleServiceImplPort() {
        return super.getPort(new QName("http://ws.sch.collaboration.luxor.acube.sds.com/", "SchScheduleServiceImplPort"), SchScheduleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SchScheduleService
     */
    @WebEndpoint(name = "SchScheduleServiceImplPort")
    public SchScheduleService getSchScheduleServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.sch.collaboration.luxor.acube.sds.com/", "SchScheduleServiceImplPort"), SchScheduleService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCHSCHEDULESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SCHSCHEDULESERVICEIMPLSERVICE_EXCEPTION;
        }
        return SCHSCHEDULESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
