
package com.sds.acube.luxor.ws.client.bbs;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BbsPostCommonService", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BbsPostCommonService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hasPostYesNo", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.HasPostYesNo")
    @ResponseWrapper(localName = "hasPostYesNoResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.HasPostYesNoResponse")
    public boolean hasPostYesNo(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "discardPost", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.DiscardPost")
    @ResponseWrapper(localName = "discardPostResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.DiscardPostResponse")
    public boolean discardPost(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "copyPost", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.CopyPost")
    @ResponseWrapper(localName = "copyPostResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.CopyPostResponse")
    public String copyPost(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.bbs.BbsBoardCategorys
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCategoryChild", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetCategoryChild")
    @ResponseWrapper(localName = "getCategoryChildResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetCategoryChildResponse")
    public BbsBoardCategorys getCategoryChild(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.bbs.BasePage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPostPaging", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetPostPaging")
    @ResponseWrapper(localName = "getPostPagingResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetPostPagingResponse")
    public BasePage getPostPaging(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        BbsBoardMaster arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectChildPostList", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectChildPostList")
    @ResponseWrapper(localName = "selectChildPostListResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectChildPostListResponse")
    public List<Object> selectChildPostList(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Object> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        BbsBoardMaster arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.bbs.BbsBoardMaster
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectBoardMasterByBoardId", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectBoardMasterByBoardId")
    @ResponseWrapper(localName = "selectBoardMasterByBoardIdResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectBoardMasterByBoardIdResponse")
    public BbsBoardMaster selectBoardMasterByBoardId(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.sds.acube.luxor.ws.client.bbs.ComCode>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectCodes", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectCodes")
    @ResponseWrapper(localName = "selectCodesResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectCodesResponse")
    public List<ComCode> selectCodes(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        BbsPostCommon arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletePost", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.DeletePost")
    @ResponseWrapper(localName = "deletePostResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.DeletePostResponse")
    public boolean deletePost(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertStatLog", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.InsertStatLog")
    @ResponseWrapper(localName = "insertStatLogResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.InsertStatLogResponse")
    public boolean insertStatLog(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.bbs.BbsPostCommon
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectPostAclAuth", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectPostAclAuth")
    @ResponseWrapper(localName = "selectPostAclAuthResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectPostAclAuthResponse")
    public BbsPostCommon selectPostAclAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectColListInfo", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectColListInfo")
    @ResponseWrapper(localName = "selectColListInfoResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectColListInfoResponse")
    public List<Object> selectColListInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.sds.acube.luxor.ws.client.bbs.ComCode>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCodeTree", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetCodeTree")
    @ResponseWrapper(localName = "getCodeTreeResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetCodeTreeResponse")
    public List<ComCode> getCodeTree(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.bbs.BbsPostCommon
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectPostById", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectPostById")
    @ResponseWrapper(localName = "selectPostByIdResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectPostByIdResponse")
    public BbsPostCommon selectPostById(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.bbs.BbsBoardCodes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCodeChild", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetCodeChild")
    @ResponseWrapper(localName = "getCodeChildResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetCodeChildResponse")
    public BbsBoardCodes getCodeChild(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.sds.acube.luxor.ws.client.bbs.BbsTag>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPostTagListByUser", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetPostTagListByUser")
    @ResponseWrapper(localName = "getPostTagListByUserResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetPostTagListByUserResponse")
    public List<BbsTag> getPostTagListByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.sds.acube.luxor.ws.client.bbs.ComCode>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectCodeByParentId", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectCodeByParentId")
    @ResponseWrapper(localName = "selectCodeByParentIdResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectCodeByParentIdResponse")
    public List<ComCode> selectCodeByParentId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        BbsPostCommon arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.sds.acube.luxor.ws.client.bbs.BbsBoardUiCru>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectColRegInfo", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectColRegInfo")
    @ResponseWrapper(localName = "selectColRegInfoResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectColRegInfoResponse")
    public List<BbsBoardUiCru> selectColRegInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.sds.acube.luxor.ws.client.bbs.BbsColumnMaster>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectColumnExInfo", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectColumnExInfo")
    @ResponseWrapper(localName = "selectColumnExInfoResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectColumnExInfoResponse")
    public List<BbsColumnMaster> selectColumnExInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.bbs.ComCode
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectCode", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectCode")
    @ResponseWrapper(localName = "selectCodeResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectCodeResponse")
    public ComCode selectCode(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        BbsPostCommon arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectPostList", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectPostList")
    @ResponseWrapper(localName = "selectPostListResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectPostListResponse")
    public List<Object> selectPostList(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectMaxPostSeq", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectMaxPostSeq")
    @ResponseWrapper(localName = "selectMaxPostSeqResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectMaxPostSeqResponse")
    public int selectMaxPostSeq(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.sds.acube.luxor.ws.client.bbs.BbsPostCommon>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectChildPost", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectChildPost")
    @ResponseWrapper(localName = "selectChildPostResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectChildPostResponse")
    public List<BbsPostCommon> selectChildPost(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hasBoardPermission", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.HasBoardPermission")
    @ResponseWrapper(localName = "hasBoardPermissionResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.HasBoardPermissionResponse")
    public boolean hasBoardPermission(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.sds.acube.luxor.ws.client.bbs.ComCode>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCodeByTraceUp", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetCodeByTraceUp")
    @ResponseWrapper(localName = "getCodeByTraceUpResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetCodeByTraceUpResponse")
    public List<ComCode> getCodeByTraceUp(
        @WebParam(name = "arg0", targetNamespace = "")
        ComCode arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.bbs.BbsPostCommon
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBoardMasterPost", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetBoardMasterPost")
    @ResponseWrapper(localName = "getBoardMasterPostResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetBoardMasterPostResponse")
    public BbsPostCommon getBoardMasterPost(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.sds.acube.luxor.ws.client.bbs.BbsHeading>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectHeading", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectHeading")
    @ResponseWrapper(localName = "selectHeadingResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectHeadingResponse")
    public List<BbsHeading> selectHeading(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        BbsPostCommon arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePostHasReply", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.UpdatePostHasReply")
    @ResponseWrapper(localName = "updatePostHasReplyResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.UpdatePostHasReplyResponse")
    public boolean updatePostHasReply(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "existUsingPost", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.ExistUsingPost")
    @ResponseWrapper(localName = "existUsingPostResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.ExistUsingPostResponse")
    public boolean existUsingPost(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hasPostRecommend", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.HasPostRecommend")
    @ResponseWrapper(localName = "hasPostRecommendResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.HasPostRecommendResponse")
    public boolean hasPostRecommend(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.bbs.BasePage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectPostPagingByType", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectPostPagingByType")
    @ResponseWrapper(localName = "selectPostPagingByTypeResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectPostPagingByTypeResponse")
    public BasePage selectPostPagingByType(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.bbs.BasePage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPostListPaging", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetPostListPaging")
    @ResponseWrapper(localName = "getPostListPagingResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetPostListPagingResponse")
    public BasePage getPostListPaging(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        BbsBoardMaster arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertPost", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.InsertPost")
    @ResponseWrapper(localName = "insertPostResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.InsertPostResponse")
    public boolean insertPost(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        BbsBoardMaster arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<BbsColumnMaster> arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        List<String> arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePostDeleteAll", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.UpdatePostDeleteAll")
    @ResponseWrapper(localName = "updatePostDeleteAllResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.UpdatePostDeleteAllResponse")
    public boolean updatePostDeleteAll(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.sds.acube.luxor.ws.client.bbs.BbsTag>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPostTag", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetPostTag")
    @ResponseWrapper(localName = "getPostTagResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetPostTagResponse")
    public List<BbsTag> getPostTag(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.bbs.BasePage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPostCommonListPaging", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetPostCommonListPaging")
    @ResponseWrapper(localName = "getPostCommonListPagingResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.GetPostCommonListPagingResponse")
    public BasePage getPostCommonListPaging(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        BbsBoardMaster arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePost", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.UpdatePost")
    @ResponseWrapper(localName = "updatePostResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.UpdatePostResponse")
    public boolean updatePost(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        BbsBoardMaster arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<BbsColumnMaster> arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        List<String> arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePostYesNo", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.UpdatePostYesNo")
    @ResponseWrapper(localName = "updatePostYesNoResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.UpdatePostYesNoResponse")
    public boolean updatePostYesNo(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.bbs.BbsPostPreNext
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectPostPreNextList", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectPostPreNextList")
    @ResponseWrapper(localName = "selectPostPreNextListResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectPostPreNextListResponse")
    public BbsPostPreNext selectPostPreNextList(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        BbsBoardMaster arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.bbs.BbsPostCommon
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectPost", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectPost")
    @ResponseWrapper(localName = "selectPostResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectPostResponse")
    public BbsPostCommon selectPost(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.bbs.BasePage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectPostPagingByNoReply", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectPostPagingByNoReply")
    @ResponseWrapper(localName = "selectPostPagingByNoReplyResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectPostPagingByNoReplyResponse")
    public BasePage selectPostPagingByNoReply(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePostType", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.UpdatePostType")
    @ResponseWrapper(localName = "updatePostTypeResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.UpdatePostTypeResponse")
    public boolean updatePostType(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.sds.acube.luxor.ws.client.bbs.BbsPostCommon>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectPostAll", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectPostAll")
    @ResponseWrapper(localName = "selectPostAllResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SelectPostAllResponse")
    public List<BbsPostCommon> selectPostAll(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveTags", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SaveTags")
    @ResponseWrapper(localName = "saveTagsResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.SaveTagsResponse")
    public boolean saveTags(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePostViewCount", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.UpdatePostViewCount")
    @ResponseWrapper(localName = "updatePostViewCountResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.UpdatePostViewCountResponse")
    public boolean updatePostViewCount(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "movePost", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.MovePost")
    @ResponseWrapper(localName = "movePostResponse", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.bbs.MovePostResponse")
    public boolean movePost(
        @WebParam(name = "arg0", targetNamespace = "")
        BbsPostCommon arg0);

}
