
package com.sds.acube.luxor.ws.client.bbs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BbsPostCommonServiceImplService", targetNamespace = "http://ws.bbs.collaboration.luxor.acube.sds.com/", wsdlLocation = "http://127.0.0.1:8080/luxor_collaboration/cxf-jaxws/MobileBoardWebServiceImplPort?wsdl")
public class BbsPostCommonServiceImplService
    extends Service
{

    private final static URL BBSPOSTCOMMONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BBSPOSTCOMMONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BBSPOSTCOMMONSERVICEIMPLSERVICE_QNAME = new QName("http://ws.bbs.collaboration.luxor.acube.sds.com/", "BbsPostCommonServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/luxor_collaboration/cxf-jaxws/MobileBoardWebServiceImplPort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BBSPOSTCOMMONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BBSPOSTCOMMONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BbsPostCommonServiceImplService() {
        super(__getWsdlLocation(), BBSPOSTCOMMONSERVICEIMPLSERVICE_QNAME);
    }

    public BbsPostCommonServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BBSPOSTCOMMONSERVICEIMPLSERVICE_QNAME, features);
    }

    public BbsPostCommonServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BBSPOSTCOMMONSERVICEIMPLSERVICE_QNAME);
    }

    public BbsPostCommonServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BBSPOSTCOMMONSERVICEIMPLSERVICE_QNAME, features);
    }

    public BbsPostCommonServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BbsPostCommonServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BbsPostCommonService
     */
    @WebEndpoint(name = "BbsPostCommonServiceImplPort")
    public BbsPostCommonService getBbsPostCommonServiceImplPort() {
        return super.getPort(new QName("http://ws.bbs.collaboration.luxor.acube.sds.com/", "BbsPostCommonServiceImplPort"), BbsPostCommonService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BbsPostCommonService
     */
    @WebEndpoint(name = "BbsPostCommonServiceImplPort")
    public BbsPostCommonService getBbsPostCommonServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.bbs.collaboration.luxor.acube.sds.com/", "BbsPostCommonServiceImplPort"), BbsPostCommonService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BBSPOSTCOMMONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BBSPOSTCOMMONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return BBSPOSTCOMMONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
