package com.sds.acube.luxor.ws.client.orgservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2014-03-26T09:07:16.494+09:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://service.org.cn.acube.sds.com/", name = "OrgProvider4WS")
public interface OrgProvider4WS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserByID", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUserByID")
    @WebMethod
    @ResponseWrapper(localName = "getUserByIDResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUserByIDResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUser getUserByID(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userID", targetNamespace = "")
        java.lang.String userID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAddressesByDONG", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetAddressesByDONG")
    @WebMethod
    @ResponseWrapper(localName = "getAddressesByDONGResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetAddressesByDONGResponse")
    public com.sds.acube.luxor.ws.client.orgservice.Addresses getAddressesByDONG(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "dong", targetNamespace = "")
        java.lang.String dong
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByDeptName", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByDeptName")
    @WebMethod
    @ResponseWrapper(localName = "getUsersByDeptNameResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByDeptNameResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUsers getUsersByDeptName(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "deptName", targetNamespace = "")
        java.lang.String deptName,
        @WebParam(name = "docsPerPage", targetNamespace = "")
        int docsPerPage,
        @WebParam(name = "currentPage", targetNamespace = "")
        int currentPage
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserByUIDWithType", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUserByUIDWithType")
    @WebMethod
    @ResponseWrapper(localName = "getUserByUIDWithTypeResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUserByUIDWithTypeResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUser getUserByUIDWithType(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userUID", targetNamespace = "")
        java.lang.String userUID,
        @WebParam(name = "type", targetNamespace = "")
        int type
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDepartment", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetDepartment")
    @WebMethod
    @ResponseWrapper(localName = "getDepartmentResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetDepartmentResponse")
    public com.sds.acube.luxor.ws.client.orgservice.Department getDepartment(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "deptID", targetNamespace = "")
        java.lang.String deptID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registerUserImage", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.RegisterUserImage")
    @WebMethod
    @ResponseWrapper(localName = "registerUserImageResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.RegisterUserImageResponse")
    public boolean registerUserImage(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userImage", targetNamespace = "")
        com.sds.acube.luxor.ws.client.orgservice.UserImage userImage
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserImage", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUserImage")
    @WebMethod
    @ResponseWrapper(localName = "getUserImageResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUserImageResponse")
    public com.sds.acube.luxor.ws.client.orgservice.UserImage getUserImage(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userUID", targetNamespace = "")
        java.lang.String userUID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkUserPWD", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.CheckUserPWD")
    @WebMethod
    @ResponseWrapper(localName = "checkUserPWDResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.CheckUserPWDResponse")
    public com.sds.acube.luxor.ws.client.orgservice.ResultInfo checkUserPWD(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userUID", targetNamespace = "")
        java.lang.String userUID,
        @WebParam(name = "userPWD", targetNamespace = "")
        java.lang.String userPWD,
        @WebParam(name = "type", targetNamespace = "")
        int type
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSignatoryFromUID", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetSignatoryFromUID")
    @WebMethod
    @ResponseWrapper(localName = "getSignatoryFromUIDResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetSignatoryFromUIDResponse")
    public com.sds.acube.luxor.ws.client.orgservice.Signatory getSignatoryFromUID(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userUID", targetNamespace = "")
        java.lang.String userUID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.Register")
    @WebMethod
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.RegisterResponse")
    public com.sds.acube.luxor.ws.client.orgservice.ResultInfo register(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "iUser", targetNamespace = "")
        com.sds.acube.luxor.ws.client.orgservice.IUser iUser,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "isEncoded", targetNamespace = "")
        int isEncoded
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDepartmentsTreeWithTD", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetDepartmentsTreeWithTD")
    @WebMethod
    @ResponseWrapper(localName = "getDepartmentsTreeWithTDResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetDepartmentsTreeWithTDResponse")
    public com.sds.acube.luxor.ws.client.orgservice.Departments getDepartmentsTreeWithTD(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userUID", targetNamespace = "")
        java.lang.String userUID,
        @WebParam(name = "treeType", targetNamespace = "")
        int treeType
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSubTitles", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetSubTitles")
    @WebMethod
    @ResponseWrapper(localName = "getSubTitlesResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetSubTitlesResponse")
    public com.sds.acube.luxor.ws.client.orgservice.Titles getSubTitles(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "titleID", targetNamespace = "")
        java.lang.String titleID,
        @WebParam(name = "compID", targetNamespace = "")
        java.lang.String compID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registerLogonPassword", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.RegisterLogonPassword")
    @WebMethod
    @ResponseWrapper(localName = "registerLogonPasswordResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.RegisterLogonPasswordResponse")
    public int registerLogonPassword(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userUID", targetNamespace = "")
        java.lang.String userUID,
        @WebParam(name = "oldSysPassword", targetNamespace = "")
        java.lang.String oldSysPassword,
        @WebParam(name = "newSysPassword", targetNamespace = "")
        java.lang.String newSysPassword
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByGradeNameWithPaging", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByGradeNameWithPaging")
    @WebMethod
    @ResponseWrapper(localName = "getUsersByGradeNameWithPagingResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByGradeNameWithPagingResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUsers getUsersByGradeNameWithPaging(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "gradeName", targetNamespace = "")
        java.lang.String gradeName,
        @WebParam(name = "orgID", targetNamespace = "")
        java.lang.String orgID,
        @WebParam(name = "type", targetNamespace = "")
        int type,
        @WebParam(name = "docsPerPage", targetNamespace = "")
        int docsPerPage,
        @WebParam(name = "currentPage", targetNamespace = "")
        int currentPage
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByNameByOrgIdWithPaging", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByNameByOrgIdWithPaging")
    @WebMethod
    @ResponseWrapper(localName = "getUsersByNameByOrgIdWithPagingResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByNameByOrgIdWithPagingResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUsers getUsersByNameByOrgIdWithPaging(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "orgID", targetNamespace = "")
        java.lang.String orgID,
        @WebParam(name = "type", targetNamespace = "")
        int type,
        @WebParam(name = "docsPerPage", targetNamespace = "")
        int docsPerPage,
        @WebParam(name = "currentPage", targetNamespace = "")
        int currentPage
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByNameByOrgId", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByNameByOrgId")
    @WebMethod
    @ResponseWrapper(localName = "getUsersByNameByOrgIdResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByNameByOrgIdResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUsers getUsersByNameByOrgId(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "orgID", targetNamespace = "")
        java.lang.String orgID,
        @WebParam(name = "type", targetNamespace = "")
        int type
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByDeptIDWithPaging", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByDeptIDWithPaging")
    @WebMethod
    @ResponseWrapper(localName = "getUsersByDeptIDWithPagingResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByDeptIDWithPagingResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUsers getUsersByDeptIDWithPaging(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "deptID", targetNamespace = "")
        java.lang.String deptID,
        @WebParam(name = "orgType", targetNamespace = "")
        int orgType,
        @WebParam(name = "docsPerPage", targetNamespace = "")
        int docsPerPage,
        @WebParam(name = "currentPage", targetNamespace = "")
        int currentPage
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getParentDepartment", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetParentDepartment")
    @WebMethod
    @ResponseWrapper(localName = "getParentDepartmentResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetParentDepartmentResponse")
    public com.sds.acube.luxor.ws.client.orgservice.Department getParentDepartment(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "deptID", targetNamespace = "")
        java.lang.String deptID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserOrganizationsByOrgID", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUserOrganizationsByOrgID")
    @WebMethod
    @ResponseWrapper(localName = "getUserOrganizationsByOrgIDResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUserOrganizationsByOrgIDResponse")
    public com.sds.acube.luxor.ws.client.orgservice.Organizations getUserOrganizationsByOrgID(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "topOrgID", targetNamespace = "")
        java.lang.String topOrgID,
        @WebParam(name = "deptID", targetNamespace = "")
        java.lang.String deptID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDepartmentsTree", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetDepartmentsTree")
    @WebMethod
    @ResponseWrapper(localName = "getDepartmentsTreeResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetDepartmentsTreeResponse")
    public com.sds.acube.luxor.ws.client.orgservice.Departments getDepartmentsTree(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userUID", targetNamespace = "")
        java.lang.String userUID,
        @WebParam(name = "treeType", targetNamespace = "")
        int treeType
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSubDuties", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetSubDuties")
    @WebMethod
    @ResponseWrapper(localName = "getSubDutiesResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetSubDutiesResponse")
    public com.sds.acube.luxor.ws.client.orgservice.Duties getSubDuties(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "dutyID", targetNamespace = "")
        java.lang.String dutyID,
        @WebParam(name = "compID", targetNamespace = "")
        java.lang.String compID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSubDepartments", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetSubDepartments")
    @WebMethod
    @ResponseWrapper(localName = "getSubDepartmentsResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetSubDepartmentsResponse")
    public com.sds.acube.luxor.ws.client.orgservice.Departments getSubDepartments(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "deptID", targetNamespace = "")
        java.lang.String deptID,
        @WebParam(name = "type", targetNamespace = "")
        int type
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registerIUserAddressInfo", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.RegisterIUserAddressInfo")
    @WebMethod
    @ResponseWrapper(localName = "registerIUserAddressInfoResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.RegisterIUserAddressInfoResponse")
    public boolean registerIUserAddressInfo(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "iUser", targetNamespace = "")
        com.sds.acube.luxor.ws.client.orgservice.IUser iUser
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDepartmentsTreeByOrgID", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetDepartmentsTreeByOrgID")
    @WebMethod
    @ResponseWrapper(localName = "getDepartmentsTreeByOrgIDResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetDepartmentsTreeByOrgIDResponse")
    public com.sds.acube.luxor.ws.client.orgservice.Departments getDepartmentsTreeByOrgID(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "orgID", targetNamespace = "")
        java.lang.String orgID,
        @WebParam(name = "treeType", targetNamespace = "")
        int treeType
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDepartmentsTreeWithDisplay", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetDepartmentsTreeWithDisplay")
    @WebMethod
    @ResponseWrapper(localName = "getDepartmentsTreeWithDisplayResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetDepartmentsTreeWithDisplayResponse")
    public com.sds.acube.luxor.ws.client.orgservice.Departments getDepartmentsTreeWithDisplay(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userUID", targetNamespace = "")
        java.lang.String userUID,
        @WebParam(name = "treeType", targetNamespace = "")
        int treeType,
        @WebParam(name = "displayType", targetNamespace = "")
        int displayType
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkDupUser", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.CheckDupUser")
    @WebMethod
    @ResponseWrapper(localName = "checkDupUserResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.CheckDupUserResponse")
    public com.sds.acube.luxor.ws.client.orgservice.ResultInfo checkDupUser(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "iUser", targetNamespace = "")
        com.sds.acube.luxor.ws.client.orgservice.IUser iUser
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByName", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByName")
    @WebMethod
    @ResponseWrapper(localName = "getUsersByNameResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByNameResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUsers getUsersByName(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserByUID", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUserByUID")
    @WebMethod
    @ResponseWrapper(localName = "getUserByUIDResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUserByUIDResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUser getUserByUID(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userUID", targetNamespace = "")
        java.lang.String userUID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByRelatedPhone", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByRelatedPhone")
    @WebMethod
    @ResponseWrapper(localName = "getUsersByRelatedPhoneResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByRelatedPhoneResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUsers getUsersByRelatedPhone(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "phoneNumber", targetNamespace = "")
        java.lang.String phoneNumber,
        @WebParam(name = "includeOfficeTel", targetNamespace = "")
        boolean includeOfficeTel,
        @WebParam(name = "includeMobile", targetNamespace = "")
        boolean includeMobile,
        @WebParam(name = "includeHomeTel", targetNamespace = "")
        boolean includeHomeTel,
        @WebParam(name = "docsPerPage", targetNamespace = "")
        int docsPerPage,
        @WebParam(name = "currentPage", targetNamespace = "")
        int currentPage
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "test", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.Test")
    @WebMethod
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.TestResponse")
    public java.lang.String test(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registerConcurrentUser", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.RegisterConcurrentUser")
    @WebMethod
    @ResponseWrapper(localName = "registerConcurrentUserResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.RegisterConcurrentUserResponse")
    public com.sds.acube.luxor.ws.client.orgservice.ResultInfo registerConcurrentUser(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "iUser", targetNamespace = "")
        com.sds.acube.luxor.ws.client.orgservice.IUser iUser
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getConcurrentUsersByID", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetConcurrentUsersByID")
    @WebMethod
    @ResponseWrapper(localName = "getConcurrentUsersByIDResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetConcurrentUsersByIDResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUsers getConcurrentUsersByID(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userID", targetNamespace = "")
        java.lang.String userID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByDeptNameWithPaging", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByDeptNameWithPaging")
    @WebMethod
    @ResponseWrapper(localName = "getUsersByDeptNameWithPagingResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByDeptNameWithPagingResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUsers getUsersByDeptNameWithPaging(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "deptName", targetNamespace = "")
        java.lang.String deptName,
        @WebParam(name = "orgID", targetNamespace = "")
        java.lang.String orgID,
        @WebParam(name = "type", targetNamespace = "")
        int type,
        @WebParam(name = "docsPerPage", targetNamespace = "")
        int docsPerPage,
        @WebParam(name = "currentPage", targetNamespace = "")
        int currentPage
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSubPositions", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetSubPositions")
    @WebMethod
    @ResponseWrapper(localName = "getSubPositionsResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetSubPositionsResponse")
    public com.sds.acube.luxor.ws.client.orgservice.Positions getSubPositions(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "positionID", targetNamespace = "")
        java.lang.String positionID,
        @WebParam(name = "compID", targetNamespace = "")
        java.lang.String compID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPolicyListByType", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetPolicyListByType")
    @WebMethod
    @ResponseWrapper(localName = "getPolicyListByTypeResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetPolicyListByTypeResponse")
    public java.util.List<com.sds.acube.luxor.ws.client.orgservice.PolicyInfo> getPolicyListByType(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "policyType", targetNamespace = "")
        int policyType
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSignatoryByID", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetSignatoryByID")
    @WebMethod
    @ResponseWrapper(localName = "getSignatoryByIDResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetSignatoryByIDResponse")
    public com.sds.acube.luxor.ws.client.orgservice.Signatory getSignatoryByID(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userID", targetNamespace = "")
        java.lang.String userID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserBySysmail", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUserBySysmail")
    @WebMethod
    @ResponseWrapper(localName = "getUserBySysmailResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUserBySysmailResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUser getUserBySysmail(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "sysmail", targetNamespace = "")
        java.lang.String sysmail
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByDeptIDList", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByDeptIDList")
    @WebMethod
    @ResponseWrapper(localName = "getUsersByDeptIDListResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByDeptIDListResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUsers getUsersByDeptIDList(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "deptIDList", targetNamespace = "")
        java.util.List<java.lang.String> deptIDList,
        @WebParam(name = "orgType", targetNamespace = "")
        int orgType
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOrganization", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetOrganization")
    @WebMethod
    @ResponseWrapper(localName = "getOrganizationResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetOrganizationResponse")
    public com.sds.acube.luxor.ws.client.orgservice.Organization getOrganization(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "deptID", targetNamespace = "")
        java.lang.String deptID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserByIDWithPWD", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUserByIDWithPWD")
    @WebMethod
    @ResponseWrapper(localName = "getUserByIDWithPWDResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUserByIDWithPWDResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUser getUserByIDWithPWD(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userID", targetNamespace = "")
        java.lang.String userID,
        @WebParam(name = "userPWD", targetNamespace = "")
        java.lang.String userPWD,
        @WebParam(name = "type", targetNamespace = "")
        int type
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDeptEmployees", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetDeptEmployees")
    @WebMethod
    @ResponseWrapper(localName = "getDeptEmployeesResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetDeptEmployeesResponse")
    public com.sds.acube.luxor.ws.client.orgservice.Employees getDeptEmployees(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "orgID", targetNamespace = "")
        java.lang.String orgID,
        @WebParam(name = "roleCode", targetNamespace = "")
        java.lang.String roleCode,
        @WebParam(name = "orgType", targetNamespace = "")
        int orgType
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByGradeName", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByGradeName")
    @WebMethod
    @ResponseWrapper(localName = "getUsersByGradeNameResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByGradeNameResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUsers getUsersByGradeName(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "gradeName", targetNamespace = "")
        java.lang.String gradeName,
        @WebParam(name = "docsPerPage", targetNamespace = "")
        int docsPerPage,
        @WebParam(name = "currentPage", targetNamespace = "")
        int currentPage
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByCompID", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByCompID")
    @WebMethod
    @ResponseWrapper(localName = "getUsersByCompIDResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByCompIDResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUsers getUsersByCompID(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "compID", targetNamespace = "")
        java.lang.String compID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkIdForInsert", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.CheckIdForInsert")
    @WebMethod
    @ResponseWrapper(localName = "checkIdForInsertResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.CheckIdForInsertResponse")
    public com.sds.acube.luxor.ws.client.orgservice.ResultInfo checkIdForInsert(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userID", targetNamespace = "")
        java.lang.String userID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByUserUIDList", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByUserUIDList")
    @WebMethod
    @ResponseWrapper(localName = "getUsersByUserUIDListResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByUserUIDListResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUsers getUsersByUserUIDList(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userUIDList", targetNamespace = "")
        java.util.List<java.lang.String> userUIDList
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSubGrades", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetSubGrades")
    @WebMethod
    @ResponseWrapper(localName = "getSubGradesResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetSubGradesResponse")
    public com.sds.acube.luxor.ws.client.orgservice.Grades getSubGrades(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "gradeID", targetNamespace = "")
        java.lang.String gradeID,
        @WebParam(name = "compID", targetNamespace = "")
        java.lang.String compID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRootDepartment", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetRootDepartment")
    @WebMethod
    @ResponseWrapper(localName = "getRootDepartmentResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetRootDepartmentResponse")
    public com.sds.acube.luxor.ws.client.orgservice.Department getRootDepartment(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkUserPWDValidation", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.CheckUserPWDValidation")
    @WebMethod
    @ResponseWrapper(localName = "checkUserPWDValidationResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.CheckUserPWDValidationResponse")
    public com.sds.acube.luxor.ws.client.orgservice.ResultInfo checkUserPWDValidation(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "iUser", targetNamespace = "")
        com.sds.acube.luxor.ws.client.orgservice.IUser iUser,
        @WebParam(name = "userPWD", targetNamespace = "")
        java.lang.String userPWD
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByDeptID", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByDeptID")
    @WebMethod
    @ResponseWrapper(localName = "getUsersByDeptIDResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.orgservice.GetUsersByDeptIDResponse")
    public com.sds.acube.luxor.ws.client.orgservice.IUsers getUsersByDeptID(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "deptID", targetNamespace = "")
        java.lang.String deptID,
        @WebParam(name = "orgType", targetNamespace = "")
        int orgType
    );
}
