package com.sds.acube.luxor.ws.client.aclservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2014-04-01T16:23:54.535+09:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://service.org.cn.acube.sds.com/", name = "AclProvider4WS")
public interface AclProvider4WS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveAccessList", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.SaveAccessList")
    @WebMethod
    @ResponseWrapper(localName = "saveAccessListResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.SaveAccessListResponse")
    public boolean saveAccessList(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "resourceID", targetNamespace = "")
        java.lang.String resourceID,
        @WebParam(name = "accessList", targetNamespace = "")
        com.sds.acube.luxor.ws.client.aclservice.AccessList accessList
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveVirtualGroupMember", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.SaveVirtualGroupMember")
    @WebMethod
    @ResponseWrapper(localName = "saveVirtualGroupMemberResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.SaveVirtualGroupMemberResponse")
    public boolean saveVirtualGroupMember(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "groupId", targetNamespace = "")
        java.lang.String groupId,
        @WebParam(name = "groupMemberInfoList", targetNamespace = "")
        java.util.List<com.sds.acube.luxor.ws.client.aclservice.GroupMemberInfo> groupMemberInfoList
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "moveByAccessString", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.MoveByAccessString")
    @WebMethod
    @ResponseWrapper(localName = "moveByAccessStringResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.MoveByAccessStringResponse")
    public boolean moveByAccessString(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "fromAccessID", targetNamespace = "")
        java.lang.String fromAccessID,
        @WebParam(name = "toAccessString", targetNamespace = "")
        java.lang.String toAccessString
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRoleIdListAllByUid", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetRoleIdListAllByUid")
    @WebMethod
    @ResponseWrapper(localName = "getRoleIdListAllByUidResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetRoleIdListAllByUidResponse")
    public java.util.List<java.lang.String> getRoleIdListAllByUid(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userUID", targetNamespace = "")
        java.lang.String userUID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "copy", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.Copy")
    @WebMethod
    @ResponseWrapper(localName = "copyResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.CopyResponse")
    public boolean copy(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "fromAccessID", targetNamespace = "")
        java.lang.String fromAccessID,
        @WebParam(name = "toAccessID", targetNamespace = "")
        java.lang.String toAccessID,
        @WebParam(name = "toAccessName", targetNamespace = "")
        java.lang.String toAccessName,
        @WebParam(name = "toAccessType", targetNamespace = "")
        int toAccessType
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVirtualGroupMemberByGroupIdWithPaging", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetVirtualGroupMemberByGroupIdWithPaging")
    @WebMethod
    @ResponseWrapper(localName = "getVirtualGroupMemberByGroupIdWithPagingResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetVirtualGroupMemberByGroupIdWithPagingResponse")
    public java.util.List<com.sds.acube.luxor.ws.client.aclservice.GroupMemberInfo> getVirtualGroupMemberByGroupIdWithPaging(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "GroupInfo", targetNamespace = "")
        com.sds.acube.luxor.ws.client.aclservice.GroupInfo groupInfo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "validSsoToken", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.ValidSsoToken")
    @WebMethod
    @ResponseWrapper(localName = "validSsoTokenResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.ValidSsoTokenResponse")
    public boolean validSsoToken(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sds.acube.luxor.ws.client.aclservice.SsoKey arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVirtualGroupList", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetVirtualGroupList")
    @WebMethod
    @ResponseWrapper(localName = "getVirtualGroupListResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetVirtualGroupListResponse")
    public java.util.List<com.sds.acube.luxor.ws.client.aclservice.GroupInfo> getVirtualGroupList(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "stringToPermission", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.StringToPermission")
    @WebMethod
    @ResponseWrapper(localName = "stringToPermissionResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.StringToPermissionResponse")
    public com.sds.acube.luxor.ws.client.aclservice.Permission stringToPermission(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "strPermission", targetNamespace = "")
        java.lang.String strPermission
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveDetail", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.SaveDetail")
    @WebMethod
    @ResponseWrapper(localName = "saveDetailResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.SaveDetailResponse")
    public boolean saveDetail(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "resourceID", targetNamespace = "")
        java.lang.String resourceID,
        @WebParam(name = "accessID", targetNamespace = "")
        java.lang.String accessID,
        @WebParam(name = "accessName", targetNamespace = "")
        java.lang.String accessName,
        @WebParam(name = "accessType", targetNamespace = "")
        int accessType,
        @WebParam(name = "privilege", targetNamespace = "")
        int privilege,
        @WebParam(name = "priority", targetNamespace = "")
        int priority
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveVirtualGroup", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.SaveVirtualGroup")
    @WebMethod
    @ResponseWrapper(localName = "saveVirtualGroupResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.SaveVirtualGroupResponse")
    public boolean saveVirtualGroup(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "groupInfo", targetNamespace = "")
        com.sds.acube.luxor.ws.client.aclservice.GroupInfo groupInfo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "makeAccessList", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.MakeAccessList")
    @WebMethod
    @ResponseWrapper(localName = "makeAccessListResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.MakeAccessListResponse")
    public com.sds.acube.luxor.ws.client.aclservice.AccessList makeAccessList(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "accessInfo", targetNamespace = "")
        java.lang.String accessInfo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveAccessList2", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.SaveAccessList2")
    @WebMethod
    @ResponseWrapper(localName = "saveAccessList2Response", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.SaveAccessList2Response")
    public boolean saveAccessList2(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "resourceID", targetNamespace = "")
        java.lang.String resourceID,
        @WebParam(name = "resourceName", targetNamespace = "")
        java.lang.String resourceName,
        @WebParam(name = "accessList", targetNamespace = "")
        com.sds.acube.luxor.ws.client.aclservice.AccessList accessList
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAccessIdListByUid", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetAccessIdListByUid")
    @WebMethod
    @ResponseWrapper(localName = "getAccessIdListByUidResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetAccessIdListByUidResponse")
    public java.util.List<java.lang.String> getAccessIdListByUid(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "userUID", targetNamespace = "")
        java.lang.String userUID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPermission", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetPermission")
    @WebMethod
    @ResponseWrapper(localName = "getPermissionResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetPermissionResponse")
    public com.sds.acube.luxor.ws.client.aclservice.Permission getPermission(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "resourceID", targetNamespace = "")
        java.lang.String resourceID,
        @WebParam(name = "accessID", targetNamespace = "")
        java.lang.String accessID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "replace", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.Replace")
    @WebMethod
    @ResponseWrapper(localName = "replaceResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.ReplaceResponse")
    public boolean replace(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "resourceIDs", targetNamespace = "")
        java.util.List<java.lang.String> resourceIDs,
        @WebParam(name = "accessInfoString", targetNamespace = "")
        java.lang.String accessInfoString
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPermissionByUid", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetPermissionByUid")
    @WebMethod
    @ResponseWrapper(localName = "getPermissionByUidResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetPermissionByUidResponse")
    public com.sds.acube.luxor.ws.client.aclservice.Permission getPermissionByUid(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "resourceID", targetNamespace = "")
        java.lang.String resourceID,
        @WebParam(name = "userUID", targetNamespace = "")
        java.lang.String userUID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPermissionByAccess", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetPermissionByAccess")
    @WebMethod
    @ResponseWrapper(localName = "getPermissionByAccessResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetPermissionByAccessResponse")
    public com.sds.acube.luxor.ws.client.aclservice.Permission getPermissionByAccess(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "resourceID", targetNamespace = "")
        java.lang.String resourceID,
        @WebParam(name = "accessIDList", targetNamespace = "")
        java.util.List<java.lang.String> accessIDList
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAccess", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetAccess")
    @WebMethod
    @ResponseWrapper(localName = "getAccessResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetAccessResponse")
    public com.sds.acube.luxor.ws.client.aclservice.Access getAccess(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "resourceID", targetNamespace = "")
        java.lang.String resourceID,
        @WebParam(name = "accessID", targetNamespace = "")
        java.lang.String accessID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getModuleVirtualGroupList", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetModuleVirtualGroupList")
    @WebMethod
    @ResponseWrapper(localName = "getModuleVirtualGroupListResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetModuleVirtualGroupListResponse")
    public java.util.List<com.sds.acube.luxor.ws.client.aclservice.GroupInfo> getModuleVirtualGroupList(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "GroupInfo", targetNamespace = "")
        com.sds.acube.luxor.ws.client.aclservice.GroupInfo groupInfo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getModuleVirtualGroupListWithPaging", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetModuleVirtualGroupListWithPaging")
    @WebMethod
    @ResponseWrapper(localName = "getModuleVirtualGroupListWithPagingResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetModuleVirtualGroupListWithPagingResponse")
    public java.util.List<com.sds.acube.luxor.ws.client.aclservice.GroupInfo> getModuleVirtualGroupListWithPaging(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "GroupInfo", targetNamespace = "")
        com.sds.acube.luxor.ws.client.aclservice.GroupInfo groupInfo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSsoToken", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetSsoToken")
    @WebMethod
    @ResponseWrapper(localName = "getSsoTokenResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetSsoTokenResponse")
    public com.sds.acube.luxor.ws.client.aclservice.SsoKey getSsoToken(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteVirtualGroup", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.DeleteVirtualGroup")
    @WebMethod
    @ResponseWrapper(localName = "deleteVirtualGroupResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.DeleteVirtualGroupResponse")
    public boolean deleteVirtualGroup(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "groupIDList", targetNamespace = "")
        java.util.List<java.lang.String> groupIDList
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteVirtualGroupMember", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.DeleteVirtualGroupMember")
    @WebMethod
    @ResponseWrapper(localName = "deleteVirtualGroupMemberResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.DeleteVirtualGroupMemberResponse")
    public boolean deleteVirtualGroupMember(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "groupId", targetNamespace = "")
        java.lang.String groupId,
        @WebParam(name = "groupMemberIDList", targetNamespace = "")
        java.util.List<java.lang.String> groupMemberIDList
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "copyByAccessString", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.CopyByAccessString")
    @WebMethod
    @ResponseWrapper(localName = "copyByAccessStringResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.CopyByAccessStringResponse")
    public boolean copyByAccessString(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "fromAccessID", targetNamespace = "")
        java.lang.String fromAccessID,
        @WebParam(name = "toAccessString", targetNamespace = "")
        java.lang.String toAccessString
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "permissionToString", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.PermissionToString")
    @WebMethod
    @ResponseWrapper(localName = "permissionToStringResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.PermissionToStringResponse")
    public java.lang.String permissionToString(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "permission", targetNamespace = "")
        int permission
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "move", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.Move")
    @WebMethod
    @ResponseWrapper(localName = "moveResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.MoveResponse")
    public boolean move(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "fromAccessID", targetNamespace = "")
        java.lang.String fromAccessID,
        @WebParam(name = "toAccessID", targetNamespace = "")
        java.lang.String toAccessID,
        @WebParam(name = "toAccessName", targetNamespace = "")
        java.lang.String toAccessName,
        @WebParam(name = "toAccessType", targetNamespace = "")
        int toAccessType
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getResourceName", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetResourceName")
    @WebMethod
    @ResponseWrapper(localName = "getResourceNameResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetResourceNameResponse")
    public java.lang.String getResourceName(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "resourceId", targetNamespace = "")
        java.lang.String resourceId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "save2", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.Save2")
    @WebMethod
    @ResponseWrapper(localName = "save2Response", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.Save2Response")
    public boolean save2(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "resourceID", targetNamespace = "")
        java.lang.String resourceID,
        @WebParam(name = "resourceName", targetNamespace = "")
        java.lang.String resourceName,
        @WebParam(name = "accessInfos", targetNamespace = "")
        java.lang.String accessInfos
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAccessList", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetAccessList")
    @WebMethod
    @ResponseWrapper(localName = "getAccessListResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetAccessListResponse")
    public com.sds.acube.luxor.ws.client.aclservice.AccessList getAccessList(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "resourceID", targetNamespace = "")
        java.lang.String resourceID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteByResourceId", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.DeleteByResourceId")
    @WebMethod
    @ResponseWrapper(localName = "deleteByResourceIdResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.DeleteByResourceIdResponse")
    public boolean deleteByResourceId(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "resourceID", targetNamespace = "")
        java.lang.String resourceID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRoleMemberUserUIDByRoleId", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetRoleMemberUserUIDByRoleId")
    @WebMethod
    @ResponseWrapper(localName = "getRoleMemberUserUIDByRoleIdResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetRoleMemberUserUIDByRoleIdResponse")
    public java.util.List<java.lang.String> getRoleMemberUserUIDByRoleId(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "roleId", targetNamespace = "")
        java.lang.String roleId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPermissionsByAccess", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetPermissionsByAccess")
    @WebMethod
    @ResponseWrapper(localName = "getPermissionsByAccessResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetPermissionsByAccessResponse")
    public com.sds.acube.luxor.ws.client.aclservice.HashMap getPermissionsByAccess(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "resourceIDList", targetNamespace = "")
        java.util.List<java.lang.String> resourceIDList,
        @WebParam(name = "accessIDList", targetNamespace = "")
        java.util.List<java.lang.String> accessIDList
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateVirtualGroup", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.UpdateVirtualGroup")
    @WebMethod
    @ResponseWrapper(localName = "updateVirtualGroupResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.UpdateVirtualGroupResponse")
    public boolean updateVirtualGroup(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "groupInfo", targetNamespace = "")
        com.sds.acube.luxor.ws.client.aclservice.GroupInfo groupInfo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "test", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.Test")
    @WebMethod
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.TestResponse")
    public java.lang.String test(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVirtualGroupMemberByGroupId", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetVirtualGroupMemberByGroupId")
    @WebMethod
    @ResponseWrapper(localName = "getVirtualGroupMemberByGroupIdResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetVirtualGroupMemberByGroupIdResponse")
    public java.util.List<com.sds.acube.luxor.ws.client.aclservice.GroupMemberInfo> getVirtualGroupMemberByGroupId(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "groupId", targetNamespace = "")
        java.lang.String groupId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAccessString", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetAccessString")
    @WebMethod
    @ResponseWrapper(localName = "getAccessStringResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetAccessStringResponse")
    public java.lang.String getAccessString(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "resourceID", targetNamespace = "")
        java.lang.String resourceID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveDetail2", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.SaveDetail2")
    @WebMethod
    @ResponseWrapper(localName = "saveDetail2Response", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.SaveDetail2Response")
    public boolean saveDetail2(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "resourceID", targetNamespace = "")
        java.lang.String resourceID,
        @WebParam(name = "resourceName", targetNamespace = "")
        java.lang.String resourceName,
        @WebParam(name = "accessID", targetNamespace = "")
        java.lang.String accessID,
        @WebParam(name = "accessName", targetNamespace = "")
        java.lang.String accessName,
        @WebParam(name = "accessType", targetNamespace = "")
        int accessType,
        @WebParam(name = "privilege", targetNamespace = "")
        int privilege,
        @WebParam(name = "priority", targetNamespace = "")
        int priority
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteAndSaveVirtualGroupMember", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.DeleteAndSaveVirtualGroupMember")
    @WebMethod
    @ResponseWrapper(localName = "deleteAndSaveVirtualGroupMemberResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.DeleteAndSaveVirtualGroupMemberResponse")
    public boolean deleteAndSaveVirtualGroupMember(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "groupId", targetNamespace = "")
        java.lang.String groupId,
        @WebParam(name = "groupMemberInfoList", targetNamespace = "")
        java.util.List<com.sds.acube.luxor.ws.client.aclservice.GroupMemberInfo> groupMemberInfoList
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRoleInfoList", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetRoleInfoList")
    @WebMethod
    @ResponseWrapper(localName = "getRoleInfoListResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetRoleInfoListResponse")
    public java.util.List<com.sds.acube.luxor.ws.client.aclservice.RoleInfo> getRoleInfoList(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVirtualGroupMemberUserUIDByGroupId", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetVirtualGroupMemberUserUIDByGroupId")
    @WebMethod
    @ResponseWrapper(localName = "getVirtualGroupMemberUserUIDByGroupIdResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetVirtualGroupMemberUserUIDByGroupIdResponse")
    public java.util.List<java.lang.String> getVirtualGroupMemberUserUIDByGroupId(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "groupId", targetNamespace = "")
        java.lang.String groupId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRoleInfoListByCondition", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetRoleInfoListByCondition")
    @WebMethod
    @ResponseWrapper(localName = "getRoleInfoListByConditionResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.GetRoleInfoListByConditionResponse")
    public java.util.List<com.sds.acube.luxor.ws.client.aclservice.RoleInfo> getRoleInfoListByCondition(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "RoleInfo", targetNamespace = "")
        com.sds.acube.luxor.ws.client.aclservice.RoleInfo roleInfo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.DeleteResponse")
    public boolean delete(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "resourceID", targetNamespace = "")
        java.lang.String resourceID,
        @WebParam(name = "accessID", targetNamespace = "")
        java.lang.String accessID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "save", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.Save")
    @WebMethod
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.org.cn.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.aclservice.SaveResponse")
    public boolean save(
        @WebParam(name = "serviceKey", targetNamespace = "")
        java.lang.String serviceKey,
        @WebParam(name = "resourceID", targetNamespace = "")
        java.lang.String resourceID,
        @WebParam(name = "accessInfos", targetNamespace = "")
        java.lang.String accessInfos
    );
}
