
package com.sds.acube.luxor.ws.client.rsc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RscResourceServiceImplService", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", wsdlLocation = "http://127.0.0.1:8080/luxor_collaboration/cxf-jaxws/MoblieServerRscResourceService?wsdl")
public class RscResourceServiceImplService
    extends Service
{

    private final static URL RSCRESOURCESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RSCRESOURCESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName RSCRESOURCESERVICEIMPLSERVICE_QNAME = new QName("http://ws.rsc.collaboration.luxor.acube.sds.com/", "RscResourceServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/luxor_collaboration/cxf-jaxws/MoblieServerRscResourceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RSCRESOURCESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        RSCRESOURCESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public RscResourceServiceImplService() {
        super(__getWsdlLocation(), RSCRESOURCESERVICEIMPLSERVICE_QNAME);
    }

    public RscResourceServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RSCRESOURCESERVICEIMPLSERVICE_QNAME, features);
    }

    public RscResourceServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, RSCRESOURCESERVICEIMPLSERVICE_QNAME);
    }

    public RscResourceServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RSCRESOURCESERVICEIMPLSERVICE_QNAME, features);
    }

    public RscResourceServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RscResourceServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RscResourceService
     */
    @WebEndpoint(name = "RscResourceServiceImplPort")
    public RscResourceService getRscResourceServiceImplPort() {
        return super.getPort(new QName("http://ws.rsc.collaboration.luxor.acube.sds.com/", "RscResourceServiceImplPort"), RscResourceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RscResourceService
     */
    @WebEndpoint(name = "RscResourceServiceImplPort")
    public RscResourceService getRscResourceServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.rsc.collaboration.luxor.acube.sds.com/", "RscResourceServiceImplPort"), RscResourceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RSCRESOURCESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw RSCRESOURCESERVICEIMPLSERVICE_EXCEPTION;
        }
        return RSCRESOURCESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
