
package com.sds.acube.luxor.ws.client.rsc;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RscResourceService", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RscResourceService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.rsc.Page
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPagingList", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetPagingList")
    @ResponseWrapper(localName = "getPagingListResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetPagingListResponse")
    public Page getPagingList(
        @WebParam(name = "arg0", targetNamespace = "")
        RscSearch arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.CreateResponse")
    public int create(
        @WebParam(name = "arg0", targetNamespace = "")
        RscResource arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReserveCount", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetReserveCount")
    @ResponseWrapper(localName = "getReserveCountResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetReserveCountResponse")
    public List<Object> getReserveCount(
        @WebParam(name = "arg0", targetNamespace = "")
        RscSearch arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRscListForRscType", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetRscListForRscType")
    @ResponseWrapper(localName = "getRscListForRscTypeResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetRscListForRscTypeResponse")
    public List<Object> getRscListForRscType(
        @WebParam(name = "arg0", targetNamespace = "")
        RscSearch arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRscListForPlace", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetRscListForPlace")
    @ResponseWrapper(localName = "getRscListForPlaceResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetRscListForPlaceResponse")
    public List<Object> getRscListForPlace(
        @WebParam(name = "arg0", targetNamespace = "")
        RscSearch arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "manageResource", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.ManageResource")
    @ResponseWrapper(localName = "manageResourceResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.ManageResourceResponse")
    public int manageResource(
        @WebParam(name = "arg0", targetNamespace = "")
        RscSearch arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllResourceList", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetAllResourceList")
    @ResponseWrapper(localName = "getAllResourceListResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetAllResourceListResponse")
    public List<Object> getAllResourceList(
        @WebParam(name = "arg0", targetNamespace = "")
        RscSearch arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.rsc.RscResource
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetResponse")
    public RscResource get(
        @WebParam(name = "arg0", targetNamespace = "")
        RscResource arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getResourceList", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetResourceList")
    @ResponseWrapper(localName = "getResourceListResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetResourceListResponse")
    public List<Object> getResourceList(
        @WebParam(name = "arg0", targetNamespace = "")
        RscSearch arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateForManage", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.UpdateForManage")
    @ResponseWrapper(localName = "updateForManageResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.UpdateForManageResponse")
    public int updateForManage(
        @WebParam(name = "arg0", targetNamespace = "")
        RscSearch arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "remove", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.Remove")
    @ResponseWrapper(localName = "removeResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.RemoveResponse")
    public int remove(
        @WebParam(name = "arg0", targetNamespace = "")
        RscResource arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.UpdateResponse")
    public int update(
        @WebParam(name = "arg0", targetNamespace = "")
        RscResource arg0);

}
