
package com.sds.acube.luxor.ws.client.rsc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RscReserveServiceImplService", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", wsdlLocation = "http://127.0.0.1:8080/luxor_collaboration/cxf-jaxws/MoblieServerRscReserveService?wsdl")
public class RscReserveServiceImplService
    extends Service
{

    private final static URL RSCRESERVESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RSCRESERVESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName RSCRESERVESERVICEIMPLSERVICE_QNAME = new QName("http://ws.rsc.collaboration.luxor.acube.sds.com/", "RscReserveServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/luxor_collaboration/cxf-jaxws/MoblieServerRscReserveService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RSCRESERVESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        RSCRESERVESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public RscReserveServiceImplService() {
        super(__getWsdlLocation(), RSCRESERVESERVICEIMPLSERVICE_QNAME);
    }

    public RscReserveServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RSCRESERVESERVICEIMPLSERVICE_QNAME, features);
    }

    public RscReserveServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, RSCRESERVESERVICEIMPLSERVICE_QNAME);
    }

    public RscReserveServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RSCRESERVESERVICEIMPLSERVICE_QNAME, features);
    }

    public RscReserveServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RscReserveServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RscReserveService
     */
    @WebEndpoint(name = "RscReserveServiceImplPort")
    public RscReserveService getRscReserveServiceImplPort() {
        return super.getPort(new QName("http://ws.rsc.collaboration.luxor.acube.sds.com/", "RscReserveServiceImplPort"), RscReserveService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RscReserveService
     */
    @WebEndpoint(name = "RscReserveServiceImplPort")
    public RscReserveService getRscReserveServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.rsc.collaboration.luxor.acube.sds.com/", "RscReserveServiceImplPort"), RscReserveService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RSCRESERVESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw RSCRESERVESERVICEIMPLSERVICE_EXCEPTION;
        }
        return RSCRESERVESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
