
package com.sds.acube.luxor.ws.client.rsc;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RscReserveService", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RscReserveService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.rsc.Page
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPagingList", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetPagingList")
    @ResponseWrapper(localName = "getPagingListResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetPagingListResponse")
    public Page getPagingList(
        @WebParam(name = "arg0", targetNamespace = "")
        RscSearch arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReserveListSinceStartDate", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetReserveListSinceStartDate")
    @ResponseWrapper(localName = "getReserveListSinceStartDateResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetReserveListSinceStartDateResponse")
    public List<Object> getReserveListSinceStartDate(
        @WebParam(name = "arg0", targetNamespace = "")
        RscSearch arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReserveList", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetReserveList")
    @ResponseWrapper(localName = "getReserveListResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetReserveListResponse")
    public List<Object> getReserveList(
        @WebParam(name = "arg0", targetNamespace = "")
        RscSearch arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.CreateResponse")
    public String create(
        @WebParam(name = "arg0", targetNamespace = "")
        RscReserve arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        RscRepeatInfo arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRscReserve", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetRscReserve")
    @ResponseWrapper(localName = "getRscReserveResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetRscReserveResponse")
    public List<Object> getRscReserve(
        @WebParam(name = "arg0", targetNamespace = "")
        RscSearch arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deliberate", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.Deliberate")
    @ResponseWrapper(localName = "deliberateResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.DeliberateResponse")
    public int deliberate(
        @WebParam(name = "arg0", targetNamespace = "")
        RscReserve arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "meetingUpdate", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.MeetingUpdate")
    @ResponseWrapper(localName = "meetingUpdateResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.MeetingUpdateResponse")
    public String meetingUpdate(
        @WebParam(name = "arg0", targetNamespace = "")
        RscReserve arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        RscRepeatInfo arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.rsc.IUser
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetUsersResponse")
    public IUser getUsers(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateReserveStatus", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.UpdateReserveStatus")
    @ResponseWrapper(localName = "updateReserveStatusResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.UpdateReserveStatusResponse")
    public int updateReserveStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        RscReserve arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createReserve", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.CreateReserve")
    @ResponseWrapper(localName = "createReserveResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.CreateReserveResponse")
    public String createReserve(
        @WebParam(name = "arg0", targetNamespace = "")
        RscReserve arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        RscRepeatInfo arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkReserveTime", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.CheckReserveTime")
    @ResponseWrapper(localName = "checkReserveTimeResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.CheckReserveTimeResponse")
    public List<Object> checkReserveTime(
        @WebParam(name = "arg0", targetNamespace = "")
        RscReserve arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.rsc.RscReserve
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetResponse")
    public RscReserve get(
        @WebParam(name = "arg0", targetNamespace = "")
        RscReserve arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.rsc.MailSendResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMail", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.SendMail")
    @ResponseWrapper(localName = "sendMailResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.SendMailResponse")
    public MailSendResult sendMail(
        @WebParam(name = "arg0", targetNamespace = "")
        ComMail arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sds.acube.luxor.ws.client.rsc.Page
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeliberateList", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetDeliberateList")
    @ResponseWrapper(localName = "getDeliberateListResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.GetDeliberateListResponse")
    public Page getDeliberateList(
        @WebParam(name = "arg0", targetNamespace = "")
        RscSearch arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "remove", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.Remove")
    @ResponseWrapper(localName = "removeResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.RemoveResponse")
    public String remove(
        @WebParam(name = "arg0", targetNamespace = "")
        RscReserve arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://ws.rsc.collaboration.luxor.acube.sds.com/", className = "com.sds.acube.luxor.ws.client.rsc.UpdateResponse")
    public String update(
        @WebParam(name = "arg0", targetNamespace = "")
        RscReserve arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        RscRepeatInfo arg1);

}
